lessons/urls.py
from django.conf.urls import patterns, url

from lessons import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^lessons/(?P<lesson_id>\d+)/$', views.lesson, name='lesson'),
    url(r'^problems/(?P<problem_id>\d+)/$', views.problem, name='problem'),
    url(r'^send_submission/(?P<problem_id>\d+)/$', views.send_submission, name='send_submission'),
    url(r'^load_submissions/$', views.load_submissions, name='load_submissions'),
    url(r'^register/$', views.register, name='register'),
)

testingplatform/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('lessons.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/$', 'django.contrib.auth.views.login', {
        'template_name': 'login.html'
    }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {
        'next_page': 'index'
    }, name='logout'),
)

lessons/models.py
from django.db import models
from django.contrib.auth.models import User


class Lesson(models.Model):
    title = models.TextField()
    content = models.TextField()

    def __str__(self):
        return self.title


class Problem(models.Model):
    title = models.TextField()
    statement = models.TextField()
    lesson = models.ForeignKey(Lesson)

    def __str__(self):
        return self.title


class Test(models.Model):
    number = models.IntegerField(unique=True)
    input = models.TextField()
    answer = models.TextField()
    problem = models.ForeignKey(Problem)

    def __str__(self):
        return '{0}: {1}'.format(self.number, self.input)


class Submission(models.Model):
    OK = 'OK'
    RE = 'RE'
    WA = 'WA'
    STATUSES = (
        (OK, 'Correct'),
        (RE, 'Run-time error'),
        (WA, 'Wrong answer'),
    )

    code = models.TextField()
    status = models.TextField(choices=STATUSES)
    problem = models.ForeignKey(Problem)
    info = models.TextField(blank=True)
    user = models.ForeignKey(User, null=True)
    time = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return '{0} (status): {1}'.format(self.problem, self.status, self.code)

    def as_dict(self):
        return {
            'id': self.id,
            'code': self.code,
            'status': self.get_status_display(),
            'info': self.info,
            'user': str(self.user),
        }

lessons/views.py
import json
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect

from lessons.models import Lesson, Problem
from lessons.submission_testing import test_submission


def index(request):
    lessons = Lesson.objects.all()
    return render(request, 'index.html', {'lessons': lessons})


def lesson(request, lesson_id):
    lesson = Lesson.objects.get(id=lesson_id)
    return render(request, 'lesson.html', {'lesson': lesson})


@login_required(login_url='/login')
def problem(request, problem_id):
    problem = Problem.objects.get(id=problem_id)
    tests = problem.test_set.order_by('number')
    return render(request, 'problem.html', {'problem': problem, 'tests': tests})


@login_required
def send_submission(request, problem_id):
    problem = Problem.objects.get(id=problem_id)
    source = request.POST['source']
    test_submission(problem, source, request.user)
    return redirect('problem', problem_id=problem.id)


def load_submissions(request):
    '''
    Ajax request.

    Params:
        problem_id

    Return: {
        'submissions': ...
    }
    '''
    problem = Problem.objects.get(id=int(request.GET['problem_id']))
    submissions_json = [submission.as_dict()
                        for submission in problem.submission_set.all()]
    response_data = {
        'submissions': submissions_json
    }

    return HttpResponse(json.dumps(response_data),
                        content_type="application/json")


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/")
    else:
        form = UserCreationForm()
    return render(request, "register.html", {
        'form': form,
    })

lessons/templates/base.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'lessons/normalize.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'lessons/foundation.min.css' %}" />

<script src="{% static 'lessons/modernizr.js' %}"></script>

<nav class="top-bar" data-topbar role="navigation">
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      {% if not user.is_anonymous %}
      <li><a href="#">{{ user }}</a></li>
      <li><a href="{% url 'logout' %}">Выйти</a></li>
      {% else %}
      <li><a href="{% url 'register' %}">Зарегистрироваться</a></li>
      <li><a href="{% url 'login' %}">Войти</a></li>
      {% endif %}
    </ul>

  </section>

  <ul class="title-area">
    <li class="name">
      <h1><a href="{% url 'index' %}">Учебник Питона</a></h1>
    </li>
  </ul>
</nav>

<div class="row">
  <div class="small-0 large-1 columns"></div>
  <div class="small-12 large-10 columns">
    {% block content %}
    {% endblock %}
  </div>
  <div class="small-0 large-1 columns"></div>
</div>

<script src="{% static 'lessons/jquery.js' %}"></script>
<script src="{% static 'lessons/foundation.min.js' %}"></script>
<script>
    $(document).foundation();
</script>

{% block scripts %}
{% endblock %}

lessons/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Уроки</h1>
    <ul>
        {% for lesson in lessons %}
        <li><a href="{% url 'lesson' lesson.id %}">{{ lesson.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

lessons/templates/lesson.html
{% extends "base.html" %}

{% block content %}
<h1>Урок {{ lesson.id }}: {{ lesson.title }}</h1>

{{ lesson.content|safe }}
<h3>Задачи</h3>
<ul>
    {% for problem in lesson.problem_set.all %}
    <li><a href='{% url 'problem' problem.id %}'>{{ problem.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

lessons/templates/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" class="button" value="login" />
<input type="hidden" class="button" name="next" value="{{ next }}" />
</form>

{% endblock %}

lessons/templates/problem.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<input type="hidden" id="problem_id" value="{{ problem.id }}">

<a href="{% url 'lesson' problem.lesson.id %}">Урок {{ problem.lesson.id }}: {{ problem.lesson.title }}</a>

<h1>Задача "{{ problem.title }}"</h1>

{{ problem.statement|safe }}

<form action="{% url 'send_submission' problem.id %}" method="post">
    {% csrf_token %}
    <textarea name="source" cols="100" rows="10">
def action(...):
    return ...
    </textarea>
    <input type="submit" class="button" value="Отправить на проверку">
</form>

<table id="submissions" border="1">
</table>
{% endblock %}

{% block scripts %}
<script src="{% static 'lessons/load_submissions.js' %}"></script>
{% endblock %}

lessons/templates/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
  <h1>Регистрация пользователя</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button" value="Зарегистрироваться">
  </form>
{% endblock %}